# Generated by Django 6.0.3 on 2026-03-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_sensortemperature_delete_co2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortemperature',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
