# Generated by Django 6.0.3 on 2026-06-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0003_alter_sensortemperature_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
