# Generated by Django 6.0.3 on 2026-06-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0004_sensornames'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorNames',
            new_name='SensorNodes',
        ),
    ]
