# Generated by Django 6.0.3 on 2026-06-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0005_rename_sensornames_sensornodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensornodes',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
